version: "3"

services:
  frontend:
    image: "nginx:alpine"
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
  backend:
    image: "devops-challenge-backend"
    build: "./backend"
    volumes:
      - "./backend:/app"
      - "~/.aws:/root/aws:ro"
    ports:
      - "5000:5000"
